### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by norayr** [btreut/a2#1]
hello, Bernhard,

thank you for having this on github.
can you sync it again?
or may be set up some script to sync it?

btw, i never was able to run A2 on my Gentoo.
alsmost never.

it almost crashes on my systems.

**Comment by norayr** [comment]
ah sorry, i just found https://github.com/metacore/A2OS in your stars.
if that's get updated, then just ignore this.

**Comment by btreut** [comment]
In the meantime I added a link to metacore's stuff and the original repo, which moved to gitlab @ ETHZ.

**Comment by Ignat99** [comment]
I would advise switching again to individual storage and taking care of backup radio communication channels.

**Comment by btreut** [comment]
> I would advise switching again to individual storage and taking care of backup radio communication channels.

hmm, I do not really understand what you try to suggest.
